apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwo-pvc
  namespace: dwo
  labels:
    app.kubernetes.io/name: dwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
